name: Builds successfully

on:
  push:
    branches:
      - "*"
      - "!release/latest"
      - "!release/v*"

env:
  NODE_VERSION: 16.x

jobs:
  check-library-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          scope: ${{ github.repository_owner }}

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.6.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v2
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Init
        run: pnpm i --ignore-scripts

      - name: Build
        run: pnpm run pack

      - name: Result
        run: ls -al ./dist
